visual_regression_test:
   stage: test
   image:
     name: docker-prod.hv.devk.de/awsplattform/vendor-images/docker.io/library/node:18.16.0-alpine3.17
     entrypoint: [""]
     pull_policy: if-not-present
   tags:
     - cloud-vprod
   variables:
     PERCY_TOKEN: ${PERCY_TOKEN}
     PERCY_TARGET: storybook-static
     PERCY_BROWSER_EXECUTABLE: /usr/bin/chromium-browser
   before_script:
     - apk update && apk add --no-cache chromium
   script:
     - which chromium || which chromium-browser
     - ls storybook-static
     - npm install
     - npm run build-storybook
     - npm run visual