visual_regression_test:
   stage: test
   image:
     name: node:18.16.0-alpine3.17
     entrypoint: [""]
   variables:
     PERCY_TOKEN: ${PERCY_TOKEN}
     PERCY_TARGET: storybook-static
     PERCY_BROWSER_EXECUTABLE: /usr/bin/chromium-browser
   before_script:
     - apk update && apk add --no-cache chromium
   script:
     - which chromium || which chromium-browser
     - ls storybook-static
     - npm install
     - npm run build-storybook
     - npm run visual
